spring:
  application:
    name: pruebaCapitole
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 10000
            readTimeout: 10000
base:
  url: https://swapi.dev/api
logging:
  level:
    root: info
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
  file:
    name: ${HOME}/app/log/pruebatecnica.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
server:
  port: 6969
  url: ${SERVER_URL:http://localhost:6969/}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  server:
    url: ${SERVER_URL:http://localhost:6969}
    description: API Server
